### ISSUE TITLE
`Flask` not working unless `Flask` set to version 2.0.1 and `python-dotenv` is set to version 0.19.0. 

### ISSUE THREAD

**Issue by firetto** [radiocosmology/padloper#68]
Setting `Flask` and `python-dotenv` to the latest versions causes the following error when trying to query the Flask server: 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/ahincks/code/hirax-layoutdb/flask-interface/api.py", line 6, in <module>
    from flask.scaffold import F
ModuleNotFoundError: No module named 'flask.scaffold'
```
Perhaps only one of `Flask` or `python-dotenv` is causing this error, but either way this needs to be investigated.

**Comment by jfitzgerald1126** [comment]
requirements updated
